var searchData=
[
  ['kbmknstatus_20tt_0',['&lt;tt&gt;kbMkNstatus&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md211',1,'']]],
  ['kbmknx_20tt_1',['&lt;tt&gt;kbMkNx&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md213',1,'']]],
  ['kbmkny_20tt_2',['&lt;tt&gt;kbMkNy&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md215',1,'']]],
  ['kbnfingers_20tt_3',['&lt;tt&gt;kbNfingers&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md209',1,'']]],
  ['kdefault_5fvolume_4',['kDefault_Volume',['../classMIDIControlHandler.html#a0f01a1400e798b9fea497af3b8f1f67ba0a9e2ed178299742fc4bb372ad89bfc8',1,'MIDIControlHandler']]],
  ['key_20n_20label_20tt_5',['&lt;tt&gt;Keyboard M - Key N - Label&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md138',1,'']]],
  ['key_20status_20tt_6',['&lt;tt&gt;Keyboard N - Send Key Status&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md158',1,'']]],
  ['key_20tt_7',['key tt',['../md_architecture_2smartKeyboard_2README.html#autotoc_md205',1,'&lt;tt&gt;key&lt;/tt&gt;'],['../md_architecture_2smartKeyboard_2README.html#autotoc_md140',1,'&lt;tt&gt;Keyboard N - Lowest Key&lt;/tt&gt;'],['../md_architecture_2smartKeyboard_2README.html#autotoc_md190',1,'&lt;tt&gt;Send Current Key&lt;/tt&gt;']]],
  ['key_20x_20tt_8',['&lt;tt&gt;Keyboard N - Send Key X&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md154',1,'']]],
  ['key_20y_20tt_9',['&lt;tt&gt;Keyboard N - Send Key Y&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md156',1,'']]],
  ['keyboard_20interface_10',['keyboard interface',['../md_architecture_2android_2README.html#autotoc_md7',1,'&quot;Multi-Keyboard&quot; Interface'],['../md_architecture_2android_2README.html#autotoc_md5',1,'Keyboard Interface']]],
  ['keyboard_20m_20key_20n_20label_20tt_11',['&lt;tt&gt;Keyboard M - Key N - Label&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md138',1,'']]],
  ['keyboard_20n_20lowest_20key_20tt_12',['&lt;tt&gt;Keyboard N - Lowest Key&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md140',1,'']]],
  ['keyboard_20n_20number_20of_20keys_20tt_13',['&lt;tt&gt;Keyboard N - Number of Keys&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md142',1,'']]],
  ['keyboard_20n_20orientation_20tt_14',['&lt;tt&gt;Keyboard N - Orientation&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md144',1,'']]],
  ['keyboard_20n_20piano_20keyboard_20tt_15',['&lt;tt&gt;Keyboard N - Piano Keyboard&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md146',1,'']]],
  ['keyboard_20n_20root_20position_20tt_16',['&lt;tt&gt;Keyboard N - Root Position&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md148',1,'']]],
  ['keyboard_20n_20scale_20tt_17',['&lt;tt&gt;Keyboard N - Scale&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md150',1,'']]],
  ['keyboard_20n_20send_20freq_20tt_18',['&lt;tt&gt;Keyboard N - Send Freq&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md152',1,'']]],
  ['keyboard_20n_20send_20key_20status_20tt_19',['&lt;tt&gt;Keyboard N - Send Key Status&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md158',1,'']]],
  ['keyboard_20n_20send_20key_20x_20tt_20',['&lt;tt&gt;Keyboard N - Send Key X&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md154',1,'']]],
  ['keyboard_20n_20send_20key_20y_20tt_21',['&lt;tt&gt;Keyboard N - Send Key Y&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md156',1,'']]],
  ['keyboard_20n_20send_20numbered_20x_20tt_22',['&lt;tt&gt;Keyboard N - Send Numbered X&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md160',1,'']]],
  ['keyboard_20n_20send_20numbered_20y_20tt_23',['&lt;tt&gt;Keyboard N - Send Numbered Y&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md162',1,'']]],
  ['keyboard_20n_20send_20x_20tt_24',['&lt;tt&gt;Keyboard N - Send X&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md164',1,'']]],
  ['keyboard_20n_20send_20y_20tt_25',['&lt;tt&gt;Keyboard N - Send Y&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md166',1,'']]],
  ['keyboard_20n_20show_20labels_20tt_26',['&lt;tt&gt;Keyboard N - Show Labels&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md168',1,'']]],
  ['keyboard_20n_20static_20mode_20tt_27',['&lt;tt&gt;Keyboard N - Static Mode&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md170',1,'']]],
  ['keyboard_20polyphony_20tt_28',['&lt;tt&gt;Max Keyboard Polyphony&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md176',1,'']]],
  ['keyboard_20slide_20tt_29',['&lt;tt&gt;Inter-Keyboard Slide&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md136',1,'']]],
  ['keyboard_20tt_30',['keyboard tt',['../md_architecture_2smartKeyboard_2README.html#autotoc_md207',1,'&lt;tt&gt;keyboard&lt;/tt&gt;'],['../md_architecture_2smartKeyboard_2README.html#autotoc_md192',1,'&lt;tt&gt;Send Current Keyboard&lt;/tt&gt;']]],
  ['keyboards_20tt_31',['&lt;tt&gt;Number of Keyboards&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md172',1,'']]],
  ['keys_32',['SmartKeyboard Configuration Keys',['../md_architecture_2smartKeyboard_2README.html#autotoc_md135',1,'']]],
  ['keys_20tt_33',['&lt;tt&gt;Keyboard N - Number of Keys&lt;/tt&gt;',['../md_architecture_2smartKeyboard_2README.html#autotoc_md142',1,'']]],
  ['know_20issues_34',['Know Issues',['../md_architecture_2nodejs_2README.html#autotoc_md107',1,'']]],
  ['known_20issue_35',['Known Issue',['../md_architecture_2esp32_2gramo-bt-midi_2components_2blemidi_2README.html#autotoc_md78',1,'']]]
];
