var searchData=
[
  ['changelog_0',['changelog',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2android_2app_2oboe_2docs_2ChangeLog.html',1,'Changelog'],['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2smartKeyboard_2android_2app_2oboe_2docs_2ChangeLog.html',1,'Changelog'],['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2max-msp_2py2max_2CHANGELOG.html',1,'Changelog']]],
  ['channel_20volume_20control_1',['Simple MIDI Controlled 16 Channel Volume Control',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2examples_2SAM_216__channel__volume_2README.html',1,'']]],
  ['chorus_2',['Chorus',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2examples_2SAM_2chorus_2README.html',1,'']]],
  ['ci_20a_3',['ci a',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2android_2app_2oboe_2README.html',1,'Oboe &lt;a href=&quot;https://github.com/google/oboe/actions&quot; &gt;&lt;img src=&quot;https://github.com/google/oboe/workflows/Build%20CI/badge.svg&quot; alt=&quot;Build CI&quot;/&gt;&lt;/a&gt;'],['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2smartKeyboard_2android_2app_2oboe_2README.html',1,'Oboe &lt;a href=&quot;https://github.com/google/oboe/actions&quot; &gt;&lt;img src=&quot;https://github.com/google/oboe/workflows/Build%20CI/badge.svg&quot; alt=&quot;Build CI&quot;/&gt;&lt;/a&gt;']]],
  ['com_20google_20oboe_20actions_20img_20src_20https_3a_20github_20com_20google_20oboe_20workflows_20build_2020ci_20badge_20svg_20alt_20build_20ci_20a_4',['com google oboe actions img src https: github com google oboe workflows build 20ci badge svg alt build ci a',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2android_2app_2oboe_2README.html',1,'Oboe &lt;a href=&quot;https://github.com/google/oboe/actions&quot; &gt;&lt;img src=&quot;https://github.com/google/oboe/workflows/Build%20CI/badge.svg&quot; alt=&quot;Build CI&quot;/&gt;&lt;/a&gt;'],['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2smartKeyboard_2android_2app_2oboe_2README.html',1,'Oboe &lt;a href=&quot;https://github.com/google/oboe/actions&quot; &gt;&lt;img src=&quot;https://github.com/google/oboe/workflows/Build%20CI/badge.svg&quot; alt=&quot;Build CI&quot;/&gt;&lt;/a&gt;']]],
  ['comparator_5',['Comparator',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2comparator_2README.html',1,'']]],
  ['contribute_6',['contribute',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2android_2app_2oboe_2apps_2fxlab_2CONTRIBUTING.html',1,'How to Contribute'],['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2smartKeyboard_2android_2app_2oboe_2apps_2fxlab_2CONTRIBUTING.html',1,'How to Contribute']]],
  ['contributing_7',['contributing',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2android_2app_2oboe_2CONTRIBUTING.html',1,'CONTRIBUTING'],['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2smartKeyboard_2android_2app_2oboe_2CONTRIBUTING.html',1,'CONTRIBUTING']]],
  ['control_8',['control',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2examples_2SAM_216__channel__volume_2README.html',1,'Simple MIDI Controlled 16 Channel Volume Control'],['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2examples_2SAM_2volume_2README.html',1,'Simple Volume Control']]],
  ['controlled_2016_20channel_20volume_20control_9',['Simple MIDI Controlled 16 Channel Volume Control',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2examples_2SAM_216__channel__volume_2README.html',1,'']]],
  ['converter_10',['converter',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2android_2app_2oboe_2src_2flowgraph_2resampler_2README.html',1,'Sample Rate Converter'],['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2smartKeyboard_2android_2app_2oboe_2src_2flowgraph_2resampler_2README.html',1,'Sample Rate Converter']]],
  ['copyright_11',['faust2smartkeyb License and Copyright',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2smartKeyboard_2LICENCE.html',1,'']]]
];
