var searchData=
[
  ['game_20sample_0',['game sample',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2android_2app_2oboe_2samples_2RhythmGame_2README.html',1,'Rhythm Game sample'],['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2smartKeyboard_2android_2app_2oboe_2samples_2RhythmGame_2README.html',1,'Rhythm Game sample']]],
  ['generator_20documentation_1',['SmartKeyboard Mobile App Generator Documentation',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2smartKeyboard_2README.html',1,'']]],
  ['github_20com_20google_20oboe_20actions_20img_20src_20https_3a_20github_20com_20google_20oboe_20workflows_20build_2020ci_20badge_20svg_20alt_20build_20ci_20a_2',['github com google oboe actions img src https: github com google oboe workflows build 20ci badge svg alt build ci a',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2android_2app_2oboe_2README.html',1,'Oboe &lt;a href=&quot;https://github.com/google/oboe/actions&quot; &gt;&lt;img src=&quot;https://github.com/google/oboe/workflows/Build%20CI/badge.svg&quot; alt=&quot;Build CI&quot;/&gt;&lt;/a&gt;'],['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2smartKeyboard_2android_2app_2oboe_2README.html',1,'Oboe &lt;a href=&quot;https://github.com/google/oboe/actions&quot; &gt;&lt;img src=&quot;https://github.com/google/oboe/workflows/Build%20CI/badge.svg&quot; alt=&quot;Build CI&quot;/&gt;&lt;/a&gt;']]],
  ['google_20oboe_20actions_20img_20src_20https_3a_20github_20com_20google_20oboe_20workflows_20build_2020ci_20badge_20svg_20alt_20build_20ci_20a_3',['google oboe actions img src https: github com google oboe workflows build 20ci badge svg alt build ci a',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2android_2app_2oboe_2README.html',1,'Oboe &lt;a href=&quot;https://github.com/google/oboe/actions&quot; &gt;&lt;img src=&quot;https://github.com/google/oboe/workflows/Build%20CI/badge.svg&quot; alt=&quot;Build CI&quot;/&gt;&lt;/a&gt;'],['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2smartKeyboard_2android_2app_2oboe_2README.html',1,'Oboe &lt;a href=&quot;https://github.com/google/oboe/actions&quot; &gt;&lt;img src=&quot;https://github.com/google/oboe/workflows/Build%20CI/badge.svg&quot; alt=&quot;Build CI&quot;/&gt;&lt;/a&gt;']]],
  ['graph_20drawing_20algorithms_4',['Graph Drawing Algorithms',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2max-msp_2py2max_2docs_2notes_2graph-drawing.html',1,'']]],
  ['guide_5',['guide',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2android_2app_2oboe_2docs_2OpenSLESMigration.html',1,'OpenSLES Migration Guide'],['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2smartKeyboard_2android_2app_2oboe_2docs_2OpenSLESMigration.html',1,'OpenSLES Migration Guide']]],
  ['guide_20to_20oboe_6',['guide to oboe',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2android_2app_2oboe_2docs_2FullGuide.html',1,'Full Guide To Oboe'],['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2smartKeyboard_2android_2app_2oboe_2docs_2FullGuide.html',1,'Full Guide To Oboe']]]
];
