var searchData=
[
  ['sample_0',['sample',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2smartKeyboard_2android_2app_2oboe_2samples_2LiveEffect_2README.html',1,'LiveEffect Sample'],['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2android_2app_2oboe_2samples_2LiveEffect_2README.html',1,'LiveEffect Sample'],['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2android_2app_2oboe_2samples_2RhythmGame_2README.html',1,'Rhythm Game sample'],['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2smartKeyboard_2android_2app_2oboe_2samples_2RhythmGame_2README.html',1,'Rhythm Game sample']]],
  ['sample_20rate_20converter_1',['sample rate converter',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2android_2app_2oboe_2src_2flowgraph_2resampler_2README.html',1,'Sample Rate Converter'],['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2smartKeyboard_2android_2app_2oboe_2src_2flowgraph_2resampler_2README.html',1,'Sample Rate Converter']]],
  ['samples_2',['samples',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2smartKeyboard_2android_2app_2oboe_2samples_2README.html',1,'Oboe Samples'],['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2android_2app_2oboe_2samples_2README.html',1,'Oboe Samples']]],
  ['sawtooth_20synth_3',['Sawtooth Synth',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2examples_2SAM_2sawtooth__synth_2README.html',1,'']]],
  ['simple_20midi_20controlled_2016_20channel_20volume_20control_4',['Simple MIDI Controlled 16 Channel Volume Control',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2examples_2SAM_216__channel__volume_2README.html',1,'']]],
  ['simple_20volume_20control_5',['Simple Volume Control',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2examples_2SAM_2volume_2README.html',1,'']]],
  ['sine_20synth_6',['Sine Synth',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2examples_2SAM_2sine__synth_2README.html',1,'']]],
  ['smartkeyboard_20mobile_20app_20generator_20documentation_7',['SmartKeyboard Mobile App Generator Documentation',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2smartKeyboard_2README.html',1,'']]],
  ['src_20https_3a_20github_20com_20google_20oboe_20workflows_20build_2020ci_20badge_20svg_20alt_20build_20ci_20a_8',['src https: github com google oboe workflows build 20ci badge svg alt build ci a',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2android_2app_2oboe_2README.html',1,'Oboe &lt;a href=&quot;https://github.com/google/oboe/actions&quot; &gt;&lt;img src=&quot;https://github.com/google/oboe/workflows/Build%20CI/badge.svg&quot; alt=&quot;Build CI&quot;/&gt;&lt;/a&gt;'],['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2smartKeyboard_2android_2app_2oboe_2README.html',1,'Oboe &lt;a href=&quot;https://github.com/google/oboe/actions&quot; &gt;&lt;img src=&quot;https://github.com/google/oboe/workflows/Build%20CI/badge.svg&quot; alt=&quot;Build CI&quot;/&gt;&lt;/a&gt;']]],
  ['storing_20python_20representations_20of_20a_20maxpat_9',['Storing Python representations of a .maxpat',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2max-msp_2py2max_2docs_2notes_2storage.html',1,'']]],
  ['strong_20drumthumper_20strong_10',['strong drumthumper strong',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2android_2app_2oboe_2samples_2drumthumper_2README.html',1,'&lt;strong&gt;DrumThumper&lt;/strong&gt;'],['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2smartKeyboard_2android_2app_2oboe_2samples_2drumthumper_2README.html',1,'&lt;strong&gt;DrumThumper&lt;/strong&gt;']]],
  ['strong_20iolib_20strong_11',['strong iolib strong',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2android_2app_2oboe_2samples_2iolib_2README.html',1,'&lt;strong&gt;iolib&lt;/strong&gt;'],['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2smartKeyboard_2android_2app_2oboe_2samples_2iolib_2README.html',1,'&lt;strong&gt;iolib&lt;/strong&gt;']]],
  ['strong_20parselib_20strong_12',['strong parselib strong',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2android_2app_2oboe_2samples_2parselib_2README.html',1,'&lt;strong&gt;parselib&lt;/strong&gt;'],['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2smartKeyboard_2android_2app_2oboe_2samples_2parselib_2README.html',1,'&lt;strong&gt;parselib&lt;/strong&gt;']]],
  ['support_13',['&lt;tt&gt;faust2api&lt;/tt&gt;: Android Support',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2api_2android_2README.html',1,'']]],
  ['svg_20alt_20build_20ci_20a_14',['svg alt build ci a',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2android_2app_2oboe_2README.html',1,'Oboe &lt;a href=&quot;https://github.com/google/oboe/actions&quot; &gt;&lt;img src=&quot;https://github.com/google/oboe/workflows/Build%20CI/badge.svg&quot; alt=&quot;Build CI&quot;/&gt;&lt;/a&gt;'],['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2smartKeyboard_2android_2app_2oboe_2README.html',1,'Oboe &lt;a href=&quot;https://github.com/google/oboe/actions&quot; &gt;&lt;img src=&quot;https://github.com/google/oboe/workflows/Build%20CI/badge.svg&quot; alt=&quot;Build CI&quot;/&gt;&lt;/a&gt;']]],
  ['synth_15',['synth',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2examples_2SAM_2sawtooth__synth_2README.html',1,'Sawtooth Synth'],['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2examples_2SAM_2sine__synth_2README.html',1,'Sine Synth']]],
  ['synthesizer_16',['Virtual Analog Synthesizer',['../md__2home_2xox_2Sync_2Fadeli2_2pfx_2share_2faust_2examples_2SAM_2virtualAnalog_2README.html',1,'']]]
];
